# Generated by Django 3.2.8 on 2021-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20211130_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
