# Generated by Django 3.2.8 on 2021-11-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='updated_at',
        ),
    ]
