# Generated by Django 3.2.8 on 2021-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20211115_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('descripcion', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('usuario', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('fecha', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('hora', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
