# Generated by Django 3.2.8 on 2021-11-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_registros'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registros',
            table=None,
        ),
    ]
