# Generated by Django 3.2.8 on 2021-11-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_alter_registros_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registros',
            table='registros',
        ),
    ]
