# Generated by Django 3.2.8 on 2021-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_registros_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('descuento', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('inicio', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('final', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
